### ISSUE TITLE
When HidHide is installed,  Logitech LG HUB uses high cpu when the Logitech G29 wheel is connected

### ISSUE THREAD

**Issue by fragmental** [ViGEm/HidHide#72] opened 2022-05-24 07:05 UTC
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://vigem.org/Community-Support/
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When HidHide is installed,  Logitech LG HUB uses high cpu (~30% on my pc) when the Logitech G29 wheel is plugged in.  When HidHide is not installed, cpu usage is normal.

### Steps to reproduce
- Have HidHide v1.1.50 Installed
- Have Logitech G HUB v2022.5.263319 installed and running
- Connect Logitech G29 racing wheel to G HUB

**Actual result:** CPU usage of G HUB rises to a high level and stays there while the wheel is connected
**Expected result:** CPU usage of G HUB should remain roughly the same as before connecting the wheel

### Machine info

**CPU-Architecture:** x64
**Windows version:** Windows 10 21H2
**Software/driver version(s):** 1.1.50

### Any other helpful information
This could very well be a problem with Logitech G HUB, but it only happens when HidHide is installed.  G HUB is not the best software.  Getting the wheel to connect often requires restarting the software, or replugging the wheel.  But the high cpu usage only happens when HidHide is installed so there must be some sort of conflict there.

**Comment by nefarius** [comment] 2022-05-24 09:02
I remember at least some other chap on Discord (or was it on GH?) reporting a similar issue. I myself currently run G HUB Version 2022.5.263319 with a Pro X Superlight and G815, smooth sailing for me 😅 

What's your blocking settings? Or is having it installed, nothing configured, enough for the issue to appear?

**Comment by fragmental** [comment] 2022-05-24 12:48
I reported it on discord, yesterday, but I think the bot might have gotten overzealous, when I made the thread, and suppressed it, or maybe I made a mistake.
 
 I have only 2 applications on the applications tab, XOutput.exe and HidHideClient.exe.  On the devices tab, only "filter-out disconnected" and "gaming devices only" is checked.  
 
 I also have a g203 and G HUB is fine when that's plugged in.

**Comment by nefarius** [comment] 2022-05-24 13:55
Oh. Bad A.I. Gonna take a look 😅

**Comment by saiyanvip** [comment] 2022-08-12 13:21
Thank you for finding and reporting the problem, I hadn't made the connection with HidHide and it turns out that I couldn't find the cause for a few days and logitech didn't help me with that.

So for the moment I uninstalled HidHide, nothing insurmountable to do without it for the moment, but I told logitech so that maybe they can pass on to the LGHUB devs to correct the problem.

**Comment by LitoHDD** [comment] 2023-01-22 13:22
I have the same problem, any solution from hidhide or do we have to wait for logitech?

**Comment by nefarius** [comment] 2023-01-22 13:24
I can't reproduce so there's nothing for me that I could do to fix and we can wait for Logitech until the end of days if nobody informs them with a proper bug report 😁

**Comment by LitoHDD** [comment] 2023-01-22 13:32
> No puedo reproducir, por lo que no hay nada que pueda hacer para solucionarlo y podemos esperar a Logitech hasta el final de los días si nadie les informa con un informe de error adecuado.😁

If I whitelist the logitech software, can it fix the problem?

**Comment by nefarius** [comment] 2023-01-22 14:19
> > No puedo reproducir, por lo que no hay nada que pueda hacer para solucionarlo y podemos esperar a Logitech hasta el final de los días si nadie les informa con un informe de error adecuado.😁
> 
> If I whitelist the logitech software, can it fix the problem?

IDK, try it.

**Comment by fragmental** [comment] 2023-01-22 23:48
My workaround was to uninstall HidHide and use HID Guardian instead.  More specifically I switched from the x360ce 3.x, or XOutput, to x360ce 4.x.  x360ce 4.x has HID Guardian built in.  You can hide devices in the devices tab of the software.  One quirk I have with x360ce 4.x is that I have to unplug and then replug my controller everytime I start the software, but it's not a big deal.

Whitelisting (or blacklist?) the lghub software sounds promising but I can't remember if I tried it or not.

I think I never sent a bug report to logitech because I couldn't find any way to send them a bug report.  It may be possible to support a bug report using the "e-mail us" link on [this page](https://www.logitechg.com/en-us/innovation/developer-lab.html)  Specifically the e-mail address is devtechsupport@logitech.com .  I might try it at a later date.

**Comment by LitoHDD** [comment] 2023-01-23 00:19
> Mi solución fue desinstalar HidHide y usar HID Guardian en su lugar. Más específicamente, cambié de x360ce 3.xo XOutput a x360ce 4.x. x360ce 4.x tiene HID Guardian incorporado. Puede ocultar dispositivos en la pestaña de dispositivos del software. Una peculiaridad que tengo con x360ce 4.x es que tengo que desconectar y volver a conectar mi controlador cada vez que inicie el software, pero no es gran cosa.
> 
> Incluir en la lista blanca (¿o en la lista negra?) el software lghub suena prometedor, pero no recuerdo si lo probe o no.
> 
> Creo que nunca envié un informe de error a logitech porque no pude encontrar ninguna forma de enviarles un informe de error. Es posible que se pueda respaldar un informe de error utilizando el enlace "envíenos un correo electrónico" en [esta página. ](https://www.logitechg.com/en-us/innovation/developer-lab.html) Específicamente, la dirección de correo electrónico es [devtechsupport@logitech.com](mailto:devtechsupport@logitech.com) . Podría intentarlo en una fecha posterior.
> 
> Editar: parece que los informes de errores también se pueden informar al [subreddit oficial de LogitechG](https://www.reddit.com/r/LogitechG/)

I have tried to put the different ghub executables in the hidhide white list and nothing remains the same without success. Hopefully in one of the new versions the problem will be corrected because I can't use the driver for that reason. It only happens when connecting the logitech g29 steering wheel, when only the mouse is there it works as it should. Let's see if @nefarius will find a solution. Because logitech technical support is not very good...

**Comment by nefarius** [comment] 2023-01-23 12:29
> Let's see if @nefarius will find a solution. Because logitech technical support is not very good...

As I said, I can't address things I cannot reproduce myself, this topic is "done" for me and simply kept open for someone else to step in. I am not actively looking into this.

**Comment by Chair4ce1** [comment] 2023-01-31 19:15
I've ran into this similar issue in the past couple days. I installed DS4windows trying to get a PS controller to work with GTA 5 that I just installed. I couldn't get the controller to work with that or the built-in support through the Steam software. So, I've gave up for now. Right away I noticed that my LGHUB Agent was taxing my processor at higher levels than normal. I went to use my G29 in American Truck Simulator and none of the buttons were working in the game. although the steering and pedals did operate normally. Also, Ghub will not show any movement of the wheel or pedals in it now.
I've gone through and erased DS4windows and I'm guessing any of it's drivers per searching the web. I've also done a Registry Edit of the wheel with no avail.
I'm now scratching my head and wishing I hadn't installed DS4windows in the first place. I'm hoping someone can figure this out and help get me back to being able to use my G29 wheel the way it was.
For all I know, it could be a Steam setting I've changed and it's causing the issue....I'm lost.

**Comment by Kanuan** [comment] 2023-01-31 19:22
If the problem was HidHide then just uninstalling HidHide through Windows' Apps and Features settings and then rebooting should fix it.

DS4Windows is not an installable software. It can't affect the system unless it's actively running, therefore if you just properly close it then it can't affect your system in any shape or form.

Other drivers used by DS4Windows also can't affect the system, they being the ViGEmBus (which is not active if ds4windows is not running) or HidHide (which you said you have uninstalled)

**Comment by Chair4ce1** [comment] 2023-01-31 19:38
> If the problem was HidHide then just uninstalling HidHide through Windows' Apps and Features settings and then rebooting should fix it.
> 
> DS4Windows is not an installable software. It can't affect the system unless it's actively running, therefore if you just properly close it then it can't affect your system in any shape or form.
> 
> Other drivers used by DS4Windows also can't affect the system, they being the ViGEmBus (which is not active if ds4windows is not running) or HidHide (which you said you have uninstalled)

**Comment by Chair4ce1** [comment] 2023-01-31 19:39
Yeah, I’ve been all over the web and following tips and advice to remove anything about DS4Windows and HidHide. Also, trying to troubleshoot G Hub and the G29 wheel. I think from here I’ll start looking into the Steam app and any settings or issues that it might have with the wheel or G hub.
Thanks for your help.

**Comment by fragmental** [comment] 2023-01-31 21:54
Try reinstalling Ghub.  I find that I have to do that periodically, even when nothing has changed.

**Comment by Chair4ce1** [comment] 2023-02-07 20:05
I'm still scratching my head here. I've completely removed GHub and then reinstalled. I believe I've removed any trace of HidHide and DS4Windows. I've also gone through the registry to make sure all the softwares are gone. I just installed G Hub again, I plug my G29 in and LGHUB Agent is the highest demanding app running. Wheel and pedals don't show movement in G Hub, but work fine in game. I can't get my wheel buttons to do anything in the game at all. I keep searching the web, but no dice. I need to be able to use every single button on the wheel for keyboard commands. It's very weird that this all started when I installed DS4Windows for a different game.

**Closed** 2023-05-02 16:41 UTC
Labels: bug

**Comment by qreeves** [comment] 2024-04-30 17:32
I'm a FOSS game developer with C++ experience who is now experiencing this issue. What can I do?

**Comment by MadsAG** [comment] 2025-10-06 12:57
Just had this issue. LGHUB Agent process took 8.5% of my Ryzen 5600X CPU when one (specific) of my two identical G29 were plugged in. Rebooting did nothing, only unplugging the specific wheel with the problem or uninstalling HidHide "solved" it (back to 0% usage).

**Comment by AriDeve** [comment] 2026-03-10 09:15
Same issue here. If you'd like me to try something for debugging or similar, let me know. Might eventually take a look at it myself, but currently don't have the time to.
